member:
    pattern:  /
    defaults: { _controller: "DigsCoreBundle:Member:index" }

member_activity:
    pattern:  /activity
    defaults: { _controller: "DigsCoreBundle:Member:activity" }
    requirements: { _method: post|put }

member_group:
    pattern:  /{id}/group/edit
    defaults: { _controller: "DigsCoreBundle:Member:group" }

member_show:
    pattern:  /{id}/show
    defaults: { _controller: "DigsCoreBundle:Member:show" }
