membergroup:
    pattern:  /
    defaults: { _controller: "DigsCoreBundle:MemberGroup:index" }

membergroup_show:
    pattern:  /{id}/show
    defaults: { _controller: "DigsCoreBundle:MemberGroup:show" }

membergroup_new:
    pattern:  /new
    defaults: { _controller: "DigsCoreBundle:MemberGroup:new" }

membergroup_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DigsCoreBundle:MemberGroup:edit" }

membergroup_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DigsCoreBundle:MemberGroup:delete" }
    requirements: { _method: post|delete }
