profile:
    pattern:  /
    defaults: { _controller: "DigsCoreBundle:Profile:index" }

profile_new:
    pattern:  /new
    defaults: { _controller: "DigsCoreBundle:Profile:new" }

profile_edit:
    pattern:  /edit
    defaults: { _controller: "DigsCoreBundle:Profile:edit" }

profile_show:
    pattern:  /{id}/show
    defaults: { _controller: "DigsCoreBundle:Profile:show" }

profile_image_show:
    pattern:  /{id}/profile.png
    defaults: { _controller: "DigsCoreBundle:Profile:showImage" }

