<?php

namespace Digs\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
	public function findMemberFile($memberId, $file)
	{
        return $this
            ->createQueryBuilder('u')
//			->select('u, m')
//			->leftJoin('u.member', 'm')
//            ->where('u.status = 1')
			->where('u.file=:file')
			->andWhere('u.typeId=:memberId')
            ->setParameter('memberId', $memberId)
            ->setParameter('file', $file)
            ->getQuery()
			->getSingleResult();
	}

	public function findAllByMemberQuery($memberId)
	{
        return $this
            ->createQueryBuilder('u')
//			->select('u, m')
//			->leftJoin('u.member', 'm')
//            ->where('u.status = 1')
			->where('u.typeId=:memberId')
            ->setParameter('memberId', $memberId)
			->orderBy('u.createdAt', 'DESC')
            ->getQuery();
	}
}
