<?php

namespace Digs\EntryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
	public function findOpenedDscQuery($num)
	{
        return $this
            ->createQueryBuilder('u')
//			->select('u, r')
//			->leftJoin('u.roles', 'r')
            ->where('u.status = 1')
//            ->setParameter('email', $username)
			->orderBy('u.id', 'DESC')
            ->getQuery();
	}
	public function findOpenedDsc($num)
	{
        return $this->findOpenedDscQuery($num)->getResult();
	}

	public function findByIdOpenedJoinMember($id)
	{
        return $this
            ->createQueryBuilder('u')
			->select('u, m, p, c, k, l')
			->leftJoin('u.member', 'm')
			->leftJoin('m.profile', 'p')
			->leftJoin('u.comments', 'c')
			->leftJoin('c.member', 'k')
			->leftJoin('k.profile', 'l')
            ->where('u.status = 1')
			->andWhere('u.id=:id')
            ->setParameter('id', $id)
            ->getQuery()
			->getSingleResult();
	}
}
