<?php

namespace Digs\EntryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
	public function findOpenedDscQueryBuilder($tag)
	{
		$qb = $this
            ->createQueryBuilder('e')
			->select('e, m, p')
			->leftJoin('e.member', 'm')
			->leftJoin('m.profile', 'p')
            ->where('e.status = 1')
			->orderBy('e.id', 'DESC')
            ;
		if ($tag)
		{
			$qb->leftJoin('e.tags', 't')
				->andWhere('t.name = :tag')
				->setParameter('tag', $tag)
			; 
		}
		return $qb;
	}
	
	public function findOpenedDsc($num)
	{
        return $this
            ->createQueryBuilder('e')
			->select('e, m, p, t')
			->leftJoin('e.member', 'm')
			->leftJoin('m.profile', 'p')
			->leftJoin('e.tags', 't')
            ->where('e.status = 1')
			->orderBy('e.id', 'DESC')
			->setMaxResults($num)
			->getQuery()->getResult();
	}

	public function findOpenedByMemberDsc($member, $num)
	{
        return $this->findOpenedDscQueryBuilder(null)
			->andWhere('m.id=:memberId')->setParameter('memberId', $member->getId())
			->setMaxResults($num)->getQuery()->getResult();
	}

	public function findByIdOpenedJoinMember($id)
	{
        return $this
            ->createQueryBuilder('u')
			->select('u, m, p, c, k, l')
			->leftJoin('u.member', 'm')
			->leftJoin('m.profile', 'p')
			->leftJoin('u.comments', 'c')
			->leftJoin('c.member', 'k')
			->leftJoin('k.profile', 'l')
            ->where('u.status = 1')
			->andWhere('u.id=:id')
			->orderBy('c.createdAt', 'DESC')
            ->setParameter('id', $id)
            ->getQuery()
			->getSingleResult();
	}
}
