<?php

namespace Digs\EntryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTagRepository extends EntityRepository
{
	public function findOneByNameOrderASC($name)
	{
		$result = $this
            ->createQueryBuilder('e')
            ->where('e.name = :name')
			->orderBy('e.id', 'ASC')
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getQuery()
			->getResult()
            ;
		if (count($result) > 0)
		{
			return $result[0];
		}
		return null;
	}
}
