<?php

namespace Digs\EntryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryAlertRepository extends EntityRepository
{
	public function findByMember($id)
	{
        return $this
            ->createQueryBuilder('u')
			->distinct('u.entry')
            ->where('u.member = :member')
            ->setParameter('member', $id)
            ->getQuery()
			->getResult();
	}
	
	public function deleteByMemberAndEntry($member, $entry)
	{
        return $this
            ->createQueryBuilder('u')
			->delete()
            ->where('u.member = :member')
            ->andWhere('u.entry = :entry')
            ->setParameter('member', $member)
            ->setParameter('entry', $entry)
			->getQuery()
			->execute();
	}
}
