digs_information:
    resource: "@DigsInformationBundle/Resources/config/routing.yml"
    prefix:   /

digs_file:
    resource: "@DigsFileBundle/Resources/config/routing.yml"
    prefix:   /

digs_photo:
    resource: "@DigsPhotoBundle/Resources/config/routing.yml"
    prefix:   /

digs_entry:
    resource: "@DigsEntryBundle/Resources/config/routing.yml"
    prefix:   /

digs_core:
    resource: "@DigsCoreBundle/Resources/config/routing.yml"
    prefix:   /
