security:
    encoders:
      Digs\CoreBundle\Entity\Member:
        algorithm: sha512
        encode_as_base64: false
        iterations: 3

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      users:
        entity: { class: DigsCoreBundle:Member }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        restore:
          pattern: ^/restore/
          security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
            logout: ~
#                path:   _logout
#                target: _demo
#            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"
            remember_me:
                key:      %secret%
                lifetime: 2592000
                path:     /
                domain:   ~
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
