security:
    encoders:
      Digs\CoreBundle\Entiry\Member:
        algorithm: sha512
        encode_as_base64: false
        iterations: 3

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      users:
        entity: { class: DigsCoreBundle:Member }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
#            form_login:
#                check_path: _security_check
#                login_path: _login
#            logout:
#                path:   _logout
#                target: _demo
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
