parameters:
#    digs_file.example.class: Digs\FileBundle\Example

services:
#    digs_file.example:
#        class: %digs_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
