parameters:
#    digs_file.example.class: Digs\FileBundle\Example

services:
    digs_file.controller:
        class: Digs\FileBundle\Services\FileService
        arguments: ["@templating", "@doctrine.orm.entity_manager", "@form.factory", "@knp_paginator", "@router"]
