Digs\LinkBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: Digs\LinkBundle\Entity\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: text
    lifecycleCallbacks: {  }
