<?php

namespace Digs\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends EntityRepository
{
	public function findByActiveTicket($ticket)
	{
        return $this
            ->createQueryBuilder('u')
            ->where('u.ticket=:ticket')
			->andWhere('u.createdAt >= :date')
			->setParameter('ticket', $ticket)
			->setParameter('date', new \DateTime('-48 hour'))
			->orderBy('u.createdAt', 'DESC')
            ->getQuery()
			->getSingleResult();
	}
}
