<?php

namespace Digs\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
	public function findAllQueryBuilder()
	{
        return $this
            ->createQueryBuilder('p')
			->select('p, m')
			->leftJoin('p.member', 'm')
			->orderBy('p.updatedAt', 'DESC')
            ;
	}
}
