<?php

namespace Digs\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestoreRepository extends EntityRepository
{
	function findByTicketAndActiveMember($ticket)
	{
        return $this
            ->createQueryBuilder('r')
			->select('r, m')
			->leftJoin('r.member', 'm')
            ->where('r.ticket = :ticket')
            ->andWhere('m.active = true')
            ->setParameter('ticket', $ticket)
            ->getQuery()
			->getSingleResult();
	}
}
