<?php

namespace Digs\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	public function findByRole($role)
	{
        return $this
            ->createQueryBuilder('u')
            ->where('u.role=:role')
			->setParameter('role', $role)
            ->getQuery()
			->getSingleResult();
	}
}
