parameters:
#    digs_entry.example.class: Digs\EntryBundle\Example

services:
    digs_entry.mymenu.item:
        class: Digs\CoreBundle\Services\MyMenuItem
        arguments:
#            - [{title: エントリの作成, path: entry_new}, {title: エントリ2, path: entry, role: ROLE_ADMIN}]
            - [{section: global, title: エントリの作成, path: entry_new, weight: 100}]
        tags:
            - { name: digs.mymenu.item }
    digs_entry.navigation.item:
        class: Digs\CoreBundle\Services\NavigationMenuItem
        arguments:
            - [{title: エントリ, path: entry, weight: 100}]
#            - [{title: エントリ, path: entry},{title: エントリ2, path: entry}]
        tags:
            - { name: digs.navigation.item }
    digs_entry.toppanel.item:
        class: Digs\CoreBundle\Services\TopPanelItem
        arguments:
            - [{controller: DigsEntryBundle:Entry:topPanel, parameters: {max: 9}, weight: 100}]
        tags:
            - { name: digs.toppanel.item }
    digs_entry.alert.item:
        class: Digs\CoreBundle\Services\AlertItem
        arguments:
            - [{controller: DigsEntryBundle:Entry:alert, parameters: {}}]
        tags:
            - { name: digs.alert.item }
    digs_entry.profilepanel.item:
        class: Digs\CoreBundle\Services\ProfilePanelItem
        arguments:
            - [{controller: DigsEntryBundle:Entry:profilePanelEntry, parameters: {max: 3}}, {controller: DigsEntryBundle:Entry:profilePanelComment, parameters: {max: 10}}, {controller: DigsEntryBundle:Entry:profilePanelTag, parameters: {}}]
        tags:
            - { name: digs.profilepanel.item }
