Digs\EntryBundle\Entity\Comment:
    type: entity
    table: entrycomment
    repositoryClass: Digs\EntryBundle\Entity\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        message:
            type: text
        createdAt:
            type: utcdatetime
            column: created_at
        status:
            type: integer
    manyToOne:
      member:
        targetEntity: Digs\CoreBundle\Entity\Member
      entry:
        targetEntity: Digs\EntryBundle\Entity\Entry
        inversedBy: comments
        
    lifecycleCallbacks: {  }
