Digs\EntryBundle\Entity\EntryComment:
    type: entity
    table: null
    repositoryClass: Digs\EntryBundle\Entity\EntryCommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        message:
            type: text
        escapedMessage:
            type: text
            column: escaped_message
            nullable: true
        createdAt:
            type: utcdatetime
            column: created_at
        status:
            type: integer
    manyToOne:
      member:
        targetEntity: Digs\CoreBundle\Entity\Member
      entry:
        targetEntity: Digs\EntryBundle\Entity\Entry
        inversedBy: comments
        
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
