Digs\EntryBundle\Entity\EntryTag:
    type: entity
    table: null
    repositoryClass: Digs\EntryBundle\Entity\EntryTagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        entries:
            targetEntity: Entry
            mappedBy: tags

    lifecycleCallbacks: {  }
