<?php

namespace Digs\LinkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
	public function findAllOrderById()
	{
        return $this
            ->createQueryBuilder('e')
			->orderBy('e.id', 'ASC')
            ->getQuery()
			->getResult()
            ;
	}
}
