parameters:
#    digs_photo.example.class: Digs\PhotoBundle\Example

services:
#    digs_photo.example:
#        class: %digs_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
