parameters:
#    digs_photo.example.class: Digs\PhotoBundle\Example

services:
    digs_photo.controller:
        class: Digs\PhotoBundle\Services\PhotoService
        arguments: ["@templating", "@doctrine.orm.entity_manager", "@form.factory", "@knp_paginator", "@router", "@digs_image_converter.manager"]
