link:
    pattern:  /
    defaults: { _controller: "DigsLinkBundle:Link:index" }

link_new:
    pattern:  /new
    defaults: { _controller: "DigsLinkBundle:Link:new" }

link_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DigsLinkBundle:Link:edit" }

link_delete:
    pattern:  /delete
    defaults: { _controller: "DigsLinkBundle:Link:delete" }
    requirements: { _method: post|delete }
