photo:
    pattern:  /
    defaults: { _controller: "DigsPhotoBundle:Photo:index" }

photo_show:
    pattern:  /{prefix}/{id}.jpg
    defaults: { _controller: "DigsPhotoBundle:Photo:show" }

photo_thumbnail_show:
    pattern:  /thumbnail/{prefix}/{id}.jpg
    defaults: { _controller: "DigsPhotoBundle:Photo:showThumbnail" }

photo_select:
    pattern:  /select
    defaults: { _controller: "DigsPhotoBundle:Photo:select" }

photo_new:
    pattern:  /new
    defaults: { _controller: "DigsPhotoBundle:Photo:new" }
    requirements: { _method: post }
