<?php

namespace Digs\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
	public function findMemberPhoto($memberId, $id)
	{
        return $this
            ->createQueryBuilder('u')
			->select('u, m')
			->leftJoin('u.member', 'm')
//			->leftJoin('m.profile', 'p')
            ->where('u.status = 1')
			->andWhere('u.file=:id')
			->andWhere('m.id=:memberId')
            ->setParameter('memberId', $memberId)
            ->setParameter('id', $id)
            ->getQuery()
			->getSingleResult();
	}
	
	public function findAllByMemberOrderByDescQuery($memberId)
	{
        return $this
            ->createQueryBuilder('u')
			->select('u, m')
			->leftJoin('u.member', 'm')
//			->leftJoin('m.profile', 'p')
            ->where('u.status = 1')
			->andWhere('m.id=:memberId')
            ->setParameter('memberId', $memberId)
			->orderBy('u.createdAt', 'DESC')
            ->getQuery();
	}
}
