parameters:
#    digs_information.example.class: Digs\InformationBundle\Example

services:
    digs_information.mymenu.item:
        class: Digs\CoreBundle\Services\MyMenuItem
        arguments:
            - [{section: admin, title: お知らせの作成, path: information_new, weight: 100, role: ROLE_INFORMATION}]
        tags:
            - { name: digs.mymenu.item }
    digs_information.navigation.item:
        class: Digs\CoreBundle\Services\NavigationMenuItem
        arguments:
            - [{title: お知らせ, path: information, weight: 200}]
        tags:
            - { name: digs.navigation.item }
    digs_information.toppanel.item:
        class: Digs\CoreBundle\Services\TopPanelItem
        arguments:
            - [{controller: DigsInformationBundle:Information:topPanel, parameters: {limit: 72}, weight: 50}]
        tags:
            - { name: digs.toppanel.item }
