file:
    pattern:  /
    defaults: { _controller: "DigsFileBundle:File:index" }

file_show:
    pattern:  /{prefix}/{file}/{title}
    defaults: { _controller: "DigsFileBundle:File:show" }

file_new:
    pattern:  /new
    defaults: { _controller: "DigsFileBundle:File:new" }
#
#file_create:
#    pattern:  /create
#    defaults: { _controller: "DigsFileBundle:File:create" }
#    requirements: { _method: post }
#
#file_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "DigsFileBundle:File:edit" }
#
#file_update:
#    pattern:  /{id}/update
#    defaults: { _controller: "DigsFileBundle:File:update" }
#    requirements: { _method: post|put }

file_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DigsFileBundle:File:delete" }
    requirements: { _method: post|delete }
