#file:
#    pattern:  /
#    defaults: { _controller: "DigsFileBundle:File:index" }
#
#file_show:
#    pattern:  /{prefix}/{file}/{title}
#    defaults: { _controller: "DigsFileBundle:File:show" }
#
#file_new:
#    pattern:  /new
#    defaults: { _controller: "DigsFileBundle:File:new" }
#file_delete:
#    pattern:  /{id}/delete
#    defaults: { _controller: "DigsFileBundle:File:delete" }
#    requirements: { _method: post|delete }
