<?php

namespace Digs\InformationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends EntityRepository
{
	public function findOpenedDscQueryBuilder()
	{
        return $this
            ->createQueryBuilder('e')
            ->where('e.status = 1')
			->orderBy('e.id', 'DESC')
            ;
	}
	public function findOpenedDsc($num)
	{
        return $this->findOpenedDscQueryBuilder()->setMaxResults($num)->getQuery()->getResult();
	}
}
