login:
    path:   /login
    defaults:  { _controller: DigsCoreBundle:Default:login }
login_check:
    path:   /login_check
logout:
    path:   /logout

digs_core_homepage:
    pattern:  /
    defaults: { _controller: DigsCoreBundle:Default:index }

DigsCoreBundle_profile:
    resource: "@DigsCoreBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

DigsCoreBundle_restore:
    resource: "@DigsCoreBundle/Resources/config/routing/restore.yml"
    prefix:   /restore
    
DigsCoreBundle_invite:
    resource: "@DigsCoreBundle/Resources/config/routing/invite.yml"
    prefix:   /invite

DigsCoreBundle_regist:
    resource: "@DigsCoreBundle/Resources/config/routing/regist.yml"
    prefix:   /regist
    