parameters:
    digs_core.mymenu_manager.class: Digs\CoreBundle\Services\MyMenuManager
    digs_core.mymenu_manager.twig.extension.class: Digs\CoreBundle\Extension\Twig\MyMenuManagerTwigExtension
    digs_core.navigation_manager.class: Digs\CoreBundle\Services\NavigationMenuManager
    digs_core.navigation_manager.twig.extension.class: Digs\CoreBundle\Extension\Twig\NavigationMenuManagerTwigExtension
    digs_core.profilepanel_manager.class: Digs\CoreBundle\Services\ProfilePanelManager
    digs_core.profilepanel_manager.twig.extension.class: Digs\CoreBundle\Extension\Twig\ProfilePanelManagerTwigExtension
    digs_core.toppanel_manager.class: Digs\CoreBundle\Services\TopPanelManager
    digs_core.toppanel_manager.twig.extension.class: Digs\CoreBundle\Extension\Twig\TopPanelManagerTwigExtension

services:
    digs_core.mymenu_manager:
        class: %digs_core.mymenu_manager.class%
    digs_core.mymenu_manager.twig.extension:
        class: %digs_core.mymenu_manager.twig.extension.class%
        arguments: [@digs_core.mymenu_manager]
        tags:
            - { name: twig.extension }
    digs_core.navigation_manager:
        class: %digs_core.navigation_manager.class%
    digs_core.navigation_manager.twig.extension:
        class: %digs_core.navigation_manager.twig.extension.class%
        arguments: [@digs_core.navigation_manager]
        tags:
            - { name: twig.extension }
    digs_core.profilepanel_manager:
        class: %digs_core.profilepanel_manager.class%
    digs_core.profilepanel_manager.twig.extension:
        class: %digs_core.profilepanel_manager.twig.extension.class%
        arguments: [@digs_core.profilepanel_manager]
        tags:
            - { name: twig.extension }
    digs_core.toppanel_manager:
        class: %digs_core.toppanel_manager.class%
    digs_core.toppanel_manager.twig.extension:
        class: %digs_core.toppanel_manager.twig.extension.class%
        arguments: [@digs_core.toppanel_manager]
        tags:
            - { name: twig.extension }
            
    digs_core.admin.action_listener:
        class: Digs\CoreBundle\EventListener\AdminListener
        arguments: [@security.context]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
# items
    digs_core.mymenu.item:
        class: Digs\CoreBundle\Services\MyMenuItem
        arguments:
            - [{title: プロフィールの変更, path: profile_edit}]
        tags:
            - { name: digs.mymenu.item }
    digs_core.navigation.item:
        class: Digs\CoreBundle\Services\NavigationMenuItem
        arguments:
            - [{title: プロフィール, path: profile}]
        tags:
            - { name: digs.navigation.item }

