parameters:
#    digs_core.example.class: Digs\CoreBundle\Example

services:
#    digs_core.example:
#        class: %digs_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
