entry:
    pattern:  /
    defaults: { _controller: "DigsEntryBundle:Entry:index" }

entry_show:
    pattern:  /{id}/show
    defaults: { _controller: "DigsEntryBundle:Entry:show" }

entry_new:
    pattern:  /new
    defaults: { _controller: "DigsEntryBundle:Entry:new" }

entry_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DigsEntryBundle:Entry:edit" }

entry_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DigsEntryBundle:Entry:delete" }
    requirements: { _method: post|delete }
