Digs\InformationBundle\Entity\Information:
    type: entity
    table: null
    repositoryClass: Digs\InformationBundle\Entity\InformationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        message:
            type: text
        escapedMessage:
            type: text
            column: escaped_message
        createdAt:
            type: utcdatetime
            column: created_at
        updatedAt:
            type: utcdatetime
            column: updated_at
        status:
            type: integer

    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setEscapedMessageValue, setUpdatedAtValue]
        preUpdate:  [setEscapedMessageValue, setUpdatedAtValue]
