Digs\PhotoBundle\Entity\Photo:
    type: entity
    table: null
    repositoryClass: Digs\PhotoBundle\Entity\PhotoRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        file:
            type: string
            length: 255
        createdAt:
            type: utcdatetime
            column: created_at
        status:
            type: integer
        typeId:
            type: string
            length: 255
            column: type_id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
